language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
script:
    - chmod +x ./gradlew
